### ISSUE TITLE
Astro build fails, when adding this library to integrations  - astro version 1.8.0

### ISSUE THREAD

**Issue by BeratS** [tatethurston/astrojs-service-worker#1]
![image](https://user-images.githubusercontent.com/7864218/214311207-461f7aba-3782-4020-b725-b720b9441c3d.png)

**Comment by tatethurston** [comment]
Hi @BeratS Could you share a working minimal reproduction? I'm not able to reproduce this.

**Comment by BeratS** [comment]
As you have written to the description, the same way I added to the project, but wen I try to serve or build the application fails,
do I need to add anything else that I am missing any file or,?

    "astro": "^1.8.0",


import { defineConfig } from "astro/config";
import serviceWorker from "astrojs-service-worker";

export default defineConfig({
  integrations: [serviceWorker()],
});

**Comment by BeratS** [comment]
It shows me and this warning while installing the library.

npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser

**Comment by BeratS** [comment]
I thinks that the problem is,
![image](https://user-images.githubusercontent.com/7864218/214373448-a4697371-50f1-4cba-a1d9-a82c9a2b1095.png)

**Comment by BeratS** [comment]
Can we able to add itself this file, or by default to take this file from installing located library.

**Comment by tatethurston** [comment]
@BeratS Are you using Windows?

**Comment by BeratS** [comment]
Yes Tate, I am using windows.

**Comment by tatethurston** [comment]
Thanks @BeratS. Could you let me know if v0.0.9 resolves this for you?

**Comment by BeratS** [comment]
Tate, I found the issue of what it is,

When I comment this library to not using it, it works,
import image from "@astrojs/image";

I can't understand what in background is happening,.

But your library seems to be working well.

**Comment by tatethurston** [comment]
Interesting, if you determine why the two plugins aren’t compatible please let me know

**Comment by BeratS** [comment]
Yes adding the two libraries together is incompatible - it throws an error, which you can not start and build the application.
