### ISSUE TITLE
When using this on Vercel it breaks Vercel comments

### ISSUE THREAD

**Issue by andrewdoro** [tatethurston/astrojs-service-worker#12]
If you enter this link first time Vercel comments would work
https://aether-stack-86mccaup0-elfandreis.vercel.app/
After another refresh it stops working. You need to clean the storage cache to make it work again

**Comment by tatethurston** [comment]
@andrewdoro can you provide a link to the source code for this project, and clarify what you mean by “it stops working”

**Comment by Jak2k** [comment]
Stops working meansyou can't use Vercel comments anymore. They aren't displayed anymore. The code isn't important. This happens with all preview pages deployed on vercel.

**Comment by tatethurston** [comment]
@Jak2k or @andrewdoro can you recreate this issue outside of Vercel?

**Comment by Jak2k** [comment]
It is not possible to recreate outside of vercel, because the bug is related to  vercel feature, which is broken by the service worker.

Vercel comments are a feature, which allows to comment on preview depoyments.
