### ISSUE TITLE
Generated page links are incorrect

### ISSUE THREAD

**Issue by kireerik** [tatethurston/astrojs-service-worker#13]
example:

generated:
- `index.html`
- `page/index.html`

expected:
- `/`
- `page`

**Comment by tatethurston** [comment]
@kireerik This is the expected behavior. It sounds like you’re requesting that this be made configurable to accommodate your hosting setup? What is the error you’re encountering? Is your web server unable to serve these assets?

**Comment by tatethurston** [comment]
@kireerik Are you running into an issue? I suspect this works as is for your use case:

https://developer.chrome.com/docs/workbox/modules/workbox-precaching/#incoming-requests-for-precached-files

**Comment by kireerik** [comment]
Yes, I think the pages are not `precached` like this as is because for example `/page` exists and is served, but `/page/index.html` is not served because it is not a valid route that I will serve. I only serve pages (and not html files).

**Comment by tatethurston** [comment]
@kireerik what are you using to serve your web pages?

**Comment by kireerik** [comment]
Firebase Hosting

**Comment by tatethurston** [comment]
@kireerik if you set [build.format](https://docs.astro.build/en/reference/configuration-reference/) ` to `page` does this resolve your issue?

I’ll think on whether I’ll have this plugin set the that, or inspect the value and configure the service worker configuration accordingly

**Comment by kireerik** [comment]
No, I don't get a response. Currently it is redirecting, but I might change it so that it would return a `404` page or the server would not respond or something like that.

There is no such [`build.format`](https://docs.astro.build/en/reference/configuration-reference/#buildformat). Only `file` and `directory` which does not make a difference.

**Comment by tatethurston** [comment]
@kireerik sorry yes I mean `file` for the build option, which will change your generated files from page/index.html to page.html. This in turn will make the service worker precache route page.html instead of page/index.html.

**Comment by kireerik** [comment]
Yes I am already using `file`, but it should point to `page` (and not to `page.html`).

**Comment by tatethurston** [comment]
@kireerik `page` and `page.html` should be handled identically: https://developer.chrome.com/docs/workbox/modules/workbox-precaching/#clean-urls. The `.html` extension is expected in the generated service worker. 

Is there a specific issue you're encountering?

**Comment by kireerik** [comment]
Yes, it is not preloaded, because it should point to the correct path (not including `.html`).

**Comment by tatethurston** [comment]
@kireerik is the site public? Can you share the link?

**Comment by kireerik** [comment]
Sure:
- [Oengi.com](https://oengi.com/)

&nbsp;
example:
- # [Refo](https://github.com/kireerik/refo)

**Comment by tatethurston** [comment]
@kireerik It doesn’t look like you have a service worker deployed to that domain. Could you deploy the service worker?

**Comment by kireerik** [comment]
Yes, I didn't introduce it because of this issue.

**Comment by tatethurston** [comment]
@kireerik I think this is a misunderstanding, as opposed to something that requires a change to this library. If you deploy a version of your site with the service worker enabled, I'm happy to help you debug.

Alternative, take a look at my blog, https://www.tatethurston.com/, which uses this library. Note that the pages are served by the service worker, even though they are requested without the `.html` extension.

**Comment by kireerik** [comment]
Maybe with your blog the reason for that is because you make them available with the `.html` extension as well.

**Comment by tatethurston** [comment]
The current settings match the defaults for most web servers. Under the hood, this library is light weight wrapper around workbox-build. If you find a way to achieve what you want using workbox build I’m happy to consider an addition to this library

**Comment by tatethurston** [comment]
@kireerik My blog is currently hosted on AWS Amplify. I pushed it to Cloudflare pages, which includes redirects to extensionless pages out of the box: https://blog-5hp.pages.dev. Note that eg `/about.html` is redirected to `/about`:

```
curl -I https://blog-5hp.pages.dev/about.html
HTTP/2 308
date: Mon, 24 Jul 2023 23:54:48 GMT
location: /about
```
And the service worker works as expected.
