### ISSUE TITLE
node_modules/astrojs-service-worker/service-worker.js.js returns a simple object which is deprecated. Please return an instance of Response. See https://docs.astro.build/en/core-concepts/endpoints/#server-endpoints-api-routes for more information.

### ISSUE THREAD

**Issue by thanogod** [tatethurston/astrojs-service-worker#19]
Hello i have upgraded my astro from 2 to 3.0.0 and it shows me that error,maybe some of your code return an simple object, i suggest seeing this:https://docs.astro.build/en/guides/upgrade-to/v3/#deprecated-returning-simple-object-in-endpoints.

**Comment by tatethurston** [comment]
Thanks @thanogod

**Comment by thanogod** [comment]
> Thanks @thanogod 

No problem,keep the good work up
