### ISSUE TITLE
Failed to register a ServiceWorker for scope

### ISSUE THREAD

**Issue by barbalex** [tatethurston/astrojs-service-worker#21]
Since astro updated to version 3 I am getting this error when navigating to a sub-route like `/leitbild`:

```
A bad HTTP response code (404) was received when fetching the script.
gabriel-software.ch/:1 Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('https://gabriel-software.ch/leitbild/') with script ('https://gabriel-software.ch/leitbild/service-worker.js'): A bad HTTP response code (404) was received when fetching the script.
```

It does not happen on the main domain.

See for instance:
- https://gabriel-software.ch/leitbild: error in dev-tools
- https://gabriel-software.ch: no error

This is my astro.config.mjs: https://github.com/barbalex/gs4/blob/master/astro.config.mjs

**Comment by tatthurs** [comment]
@barbalex What version of astrojs-service-worker are you using?

**Comment by tatethurston** [comment]
@barbalex What version of atrojs-service-worker are you using?

**Comment by tatethurston** [comment]
Thanks. Is your repo private? I can't open your astro.config.mjs link

**Comment by tatethurston** [comment]
@barbalex I'm not seeing any errors in dev tools when navigating to https://gabriel-software.ch/leitbild: on Chrome

**Comment by barbalex** [comment]
> Is your repo private? I can't open your astro.config.mjs link

Uups. It was not meant to be private. I changed that now. Thanks for noticing.

> I'm not seeing any errors

omg. Probably updating to v1.1.0 solved the underlying issue (due to https://github.com/tatethurston/astrojs-service-worker/pull/20) but the browser cache must have caught me there. Meanwhile I see no errors any more too. Sorry for bugging you.

Thanks for this great tool.

**Comment by tatethurston** [comment]
No problem, let me know if you encounter any other issues
