### ISSUE TITLE
Support Astro 4.0

### ISSUE THREAD

**Issue by brandon-pereira** [tatethurston/astrojs-service-worker#22]
Astro 4.0 just dropped, upon upgrading my repo to Astro 4.0 I get a warning in the console when running the app:

```
20:59:24 [WARN] The injected route "/service-worker.js" by astrojs-service-worker specifies the entry point with the "entryPoint" property. This property is deprecated, please use "entrypoint" instead.
```

It seems to still work as expected during a build, so likely this is a non-breaking upgrade besides using the new field.

Relevant upstream PR: https://github.com/withastro/astro/pull/9161

**Comment by brandon-pereira** [comment]
Wow, so quick! Thanks!

**Comment by tatethurston** [comment]
> Wow, so quick! Thanks!

All the credit goes to @alexandertrefz
