### ISSUE TITLE
Page does not work offline.

### ISSUE THREAD

**Issue by titsex** [tatethurston/astrojs-service-worker#3]
Hello! He did not create the service-worker file.js, I created it myself, empty.

![image](https://user-images.githubusercontent.com/61911688/214679599-b56daa81-b01a-4892-84aa-3479c884f9ab.png)
![image](https://user-images.githubusercontent.com/61911688/214679727-07792c9c-4cfd-45a7-8b85-704e9c7d9abe.png)
![image](https://user-images.githubusercontent.com/61911688/214679808-ce886392-da1f-482a-b573-a3ffb109f176.png)

**Comment by tatethurston** [comment]
Here is a minimal example using astro 1.8.0 that is working: https://stackblitz.com/edit/astro-pxnduw. As you can see, `service-worker.js` is generated in the `dist` folder.

Could you please reproduce the error you're seeing by forking this example and sharing the url here?

**Comment by titsex** [comment]
Hi! I am using the latest version of astro (2.0.2)

I followed all the instructions.

Launched astro build && astro preview and got an error!

In Application, the service worker has the status "trying to install"

Here is the launch with the "astrojs-service-worker" plugin disabled:
![image](https://user-images.githubusercontent.com/61911688/215285521-6311b5f4-2e2e-47b0-acf0-b25d72318a03.png)

And here is the launch with the "astrojs-service-worker" plugin enabled:
![image](https://user-images.githubusercontent.com/61911688/215285648-781d4696-41a5-4837-b639-fcd2df1f4f17.png)

P.S: Before launching astro build && astro preview, I didn't forget to delete the previous dist folder.

**Comment by tatethurston** [comment]
@titsex Thanks for reporting. This build error looks windows specific. This error looks like an invalid windows path being passed to `workbox-build`. I've published v0.0.9 which should fix this. Try it out and let me know.

**Comment by titsex** [comment]
> @titsex Thanks for reporting. This build error looks windows specific. This error looks like an invalid windows path being passed to `workbox-build`. I've published v0.0.9 which should fix this. Try it out and let me know.

Thank you friend! Now everything works.

I understand that you didn't use the path module from Node.JS for some reason.

The package is very cool, thanks for the responsiveness and help!

![image](https://user-images.githubusercontent.com/61911688/215297183-cafa18e4-9805-4bf5-8fd2-5b975ab4d822.png)
