### ISSUE TITLE
ENOENT: no such file or directory, open 'C:\C:\Users\alexa\gs4\node_modules\astrojs-service-worker\noop-service-worker.js'

### ISSUE THREAD

**Issue by barbalex** [tatethurston/astrojs-service-worker#5]
I followed the instructions to install. Since then, I get this error on `npm run dev`:

```
Error: ENOENT: no such file or directory, open 'C:\C:\Users\alexa\gs4\node_modules\astrojs-service-worker\noop-service-worker.js'
```

Somehow the path got mangled, see the `C:\C:\` it starts with.
As you can see from the path I work on Windows.

This is my astro.config.mjs:
```js
import { defineConfig } from 'astro/config'
import sitemap from '@astrojs/sitemap'
import serviceWorker from 'astrojs-service-worker'

import prefetch from '@astrojs/prefetch'

// https://astro.build/config
export default defineConfig({
  site: 'https://gabriel-software.ch',
  integrations: [serviceWorker(), sitemap(), prefetch()],
})
```

and this my package.json:
```json
{
  "name": "gs4",
  "description": "Gabriel Software's website",
  "type": "module",
  "version": "2.0.0",
  "author": "Alexander Gabriel",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro",
    "deploy": "vercel build && vercel deploy --prebuilt",
    "deploy_productive": "vercel build --prod && vercel deploy --prebuilt --prod"
  },
  "dependencies": {
    "@astrojs/prefetch": "0.2.1",
    "@astrojs/sitemap": "1.2.1",
    "@types/leaflet": "1.9.2",
    "@types/react": "18.0.28",
    "@types/react-dom": "18.0.11",
    "astro": "2.1.3",
    "astro-icon": "0.8.0",
    "astrojs-service-worker": "0.0.9",
    "leaflet": "1.9.3",
    "vercel": "28.16.15"
  },
  "devDependencies": {
    "copyfiles": "2.4.1",
    "prettier": "2.8.4"
  },
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/barbalex/gs4"
  }
}
```

**Comment by barbalex** [comment]
So far I could only find one other similar case: https://stackoverflow.com/questions/46745014/alternative-for-dirname-in-node-js-when-using-es6-modules#comment111070907_53582084

**Comment by barbalex** [comment]
Hm. I am not a node expert. But from I can tell here (https://github.com/nodejs/node/issues/37845#issuecomment-974158073), a different method should be used to create the path, using `fileURLToPath` instead of `new URL`. If not, it does not work in windows.

I _think_ that should be applied to https://github.com/tatethurston/astrojs-service-worker/blob/main/src/service-worker.js.js#L6

**Comment by barbalex** [comment]
So `import.meta.url` gives: `'file:///C:/Users/alexa/gs4/node_modules/astrojs-service-worker/service-worker.js.js'`

Comparing two ways to fetch the path:

1. `new URL("./noop-service-worker.js", import.meta.url).pathname`:<br/>`/C:/Users/alexa/gs4/node_modules/astrojs-service-worker/noop-service-worker.js`
2. `url.fileURLToPath(import.meta.url)`:<br/>`C:\\Users\\alexa\\gs4\\node_modules\\astrojs-service-worker\\service-worker.js.js`

I now patched service-worker.js.js to look like this: 
```js
import { readFile } from "node:fs/promises";
import * as url from 'url';

export async function get() {
    const sw = await readFile(
    // eslint-disable-next-line no-undef
    url.fileURLToPath(import.meta.url), { encoding: "utf8" });
    return {
        body: sw,
    };
}
```

And it works for me on my windows machine.

Will test on my mac also.

**Comment by barbalex** [comment]
o.k., also works on my MacBook pro. Will create a pull request.

**Comment by tatethurston** [comment]
Thanks for the report and for digging in here @barbalex.
